name: deploy-pr

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/deploy-pr.yaml'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: utuntu-latest # OSを指定
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5 # https://github.com/docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 # https://github.com/docker/login-action?tab=readme-ov-file
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5 # https://github.com/docker/build-push-action
        with:
          context: app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}