name: deploy-pr

on:
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/deploy-pr.yaml'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    outputs:
      IMAGE_FULL_NAME: ${{ steps.meta.outputs.tags }}
    runs-on: ubuntu-latest # OSを指定
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5 # https://github.com/docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 # https://github.com/docker/login-action?tab=readme-ov-file
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5 # https://github.com/docker/build-push-action
        with:
          context: app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  # update-kubernetes-manifest:
  #   runs-on: ubuntu-latest
  #   needs: [build-and-push-image]
  #   steps:
  #     -
  #       name: Checkout repository
  #       uses: actions/checkout@v4
  #     -
  #       name: Update fastapi-sample images
  #       env:
  #         IMAGE_FULL_NAME: ${{ needs.build-and-push-image.outputs.IMAGE_FULL_NAME }}
  #       run: |
  #         yq -i "(.spec.template.spec.containers[] | select(.name == \"fastapi-sample\")).image = \"$IMAGE_FULL_NAME\""  manifests/fastapi-sample/deployment.yaml

  #     -
  #       name: Create PR # https://github.com/marketplace/actions/create-pull-request
  #       uses: peter-evans/create-pull-request@v6
  #       with:
  #         base: main
  #         title: "Update fastapi-sample"
  #         draft: true
  #         body: |
  #           # Changes
  #           - Update `fastapi-sample` image to ${{ needs.build-and-push-image.outputs.IMAGE_FULL_NAME }}

